"""prueba

Revision ID: b7f20ae2d7cb
Revises: 3465deb081e1
Create Date: 2025-06-13 02:01:13.365975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7f20ae2d7cb'
down_revision: Union[str, None] = '3465deb081e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('estadoCategoria', sa.String(length=45), nullable=True),
    sa.Column('nombreCategoria', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('idCategoria')
    )
    op.create_table('tipoAsesoria',
    sa.Column('idTipoAsesoria', sa.Integer(), nullable=False),
    sa.Column('nombreTipoAsesoria', sa.String(length=50), nullable=True),
    sa.Column('descripcionTipoAsesoria', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idTipoAsesoria')
    )
    op.create_table('blogExperiencia',
    sa.Column('idBlogExperiencia', sa.Integer(), nullable=False),
    sa.Column('fechaPublicidadBlogExperiencia', sa.String(length=500), nullable=True),
    sa.Column('usuarioIdBlogExperiencia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioIdBlogExperiencia'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idBlogExperiencia')
    )
    op.create_table('galeriaVehiculoModificado',
    sa.Column('idGaleriaVehiculoModificado', sa.Integer(), nullable=False),
    sa.Column('nombreVehiculoGaleriaVehiculoModificado', sa.String(length=100), nullable=True),
    sa.Column('descripcionGaleriaVehiculoModificado', sa.String(length=100), nullable=True),
    sa.Column('usuarioIdGaleriaVehiculoModificado', sa.Integer(), nullable=True),
    sa.Column('vehiculoIdGaleriaVehiculoModificado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioIdGaleriaVehiculoModificado'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['vehiculoIdGaleriaVehiculoModificado'], ['vehiculo.idVehiculo'], ),
    sa.PrimaryKeyConstraint('idGaleriaVehiculoModificado')
    )
    op.create_table('historialAsesoria',
    sa.Column('idHistorialAsesoria', sa.Integer(), nullable=False),
    sa.Column('comentariosHistorialAsesoria', sa.String(length=500), nullable=True),
    sa.Column('fechaRegistroHistorialAsesoria', sa.Date(), nullable=True),
    sa.Column('asesoriaIdHistorialAsesoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asesoriaIdHistorialAsesoria'], ['asesoria.idAsesoria'], ),
    sa.PrimaryKeyConstraint('idHistorialAsesoria')
    )
    op.drop_table('tipoasesoria')
    op.drop_table('blogexperiencia')
    op.drop_table('historialasesoria')
    op.drop_table('galeriavehiculomodificado')
    op.drop_constraint(op.f('asesoria_ibfk_2'), 'asesoria', type_='foreignkey')
    op.create_foreign_key(None, 'asesoria', 'tipoAsesoria', ['tipoAsesoriaIdAsesoria'], ['idTipoAsesoria'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asesoria', type_='foreignkey')
    op.create_foreign_key(op.f('asesoria_ibfk_2'), 'asesoria', 'tipoasesoria', ['tipoAsesoriaIdAsesoria'], ['idTipoAsesoria'])
    op.create_table('galeriavehiculomodificado',
    sa.Column('idGaleriaVehiculoModificado', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombreVehiculoGaleriaVehiculoModificado', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcionGaleriaVehiculoModificado', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('usuarioIdGaleriaVehiculoModificado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vehiculoIdGaleriaVehiculoModificado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuarioIdGaleriaVehiculoModificado'], ['usuario.idUsuario'], name=op.f('galeriavehiculomodificado_ibfk_1')),
    sa.ForeignKeyConstraint(['vehiculoIdGaleriaVehiculoModificado'], ['vehiculo.idVehiculo'], name=op.f('galeriavehiculomodificado_ibfk_2')),
    sa.PrimaryKeyConstraint('idGaleriaVehiculoModificado'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historialasesoria',
    sa.Column('idHistorialAsesoria', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comentariosHistorialAsesoria', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('fechaRegistroHistorialAsesoria', sa.DATE(), nullable=True),
    sa.Column('asesoriaIdHistorialAsesoria', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asesoriaIdHistorialAsesoria'], ['asesoria.idAsesoria'], name=op.f('historialasesoria_ibfk_1')),
    sa.PrimaryKeyConstraint('idHistorialAsesoria'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('blogexperiencia',
    sa.Column('idBlogExperiencia', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fechaPublicidadBlogExperiencia', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('usuarioIdBlogExperiencia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuarioIdBlogExperiencia'], ['usuario.idUsuario'], name=op.f('blogexperiencia_ibfk_1')),
    sa.PrimaryKeyConstraint('idBlogExperiencia'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipoasesoria',
    sa.Column('idTipoAsesoria', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombreTipoAsesoria', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('descripcionTipoAsesoria', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idTipoAsesoria'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('historialAsesoria')
    op.drop_table('galeriaVehiculoModificado')
    op.drop_table('blogExperiencia')
    op.drop_table('tipoAsesoria')
    op.drop_table('prueba')
    # ### end Alembic commands ###
